name: 'ZipArtifact'
description: 'Zip specified artifact.'
inputs:
  zip_name:
    description: 'Zip file name.'
    required: true
  src_dir_path:
    description: 'Source dir path.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Zip artifact - powershell
      run: |
        $Env:INPUT_ZIP_NAME = "${{ inputs.zip_name }}"
        $Env:INPUT_SRC_DIR_PATH = "${{ inputs.src_dir_path }}"
        ./.github/actions/zip_artifact/powershell/zip_artifact.ps1
      shell: powershell
