name: 'ZipArtifact'
description: 'Zip specified artifact.'
inputs:
  zip_name:
    description: 'Zip file name.'
    required: true
  src_dir_path:
    description: 'Source dir path.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Zip artifact - bash
      run: |
        export INPUT_ZIP_NAME=${{ inputs.zip_name }}
        export INPUT_SRC_DIR_PATH=${{ inputs.src_dir_path }}
        ./.github/actions/zip_artifact/bash/zip_artifact.sh
      shell: bash
