name: Build Unreal Plugin

on: push

env:
  CPP_SDK_TAG: "2.2.5"
  CPP_SDK_DESTINATION: "DolbyIO/Source/ThirdParty"
  CPP_SDK_URL: "https://github.com/DolbyIO/comms-sdk-cpp/releases/download"
  UNREAL_PLUGIN_OUTPUT: "Build/DolbyIO"
  RETENTION: 8

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        version: ["4.27", "5.0"]
    runs-on: ["self-hosted", "X64", "macOS"]
    env:
      BUILD_PLATFORM: 'macos64'
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Download C++ SDK release asset
        uses: ./.github/actions/download_cpp/bash
        with:
          url: ${{ env.CPP_SDK_URL }}
          tag: ${{ env.CPP_SDK_TAG }}
          asset_name: "cppsdk-${{ env.CPP_SDK_TAG }}-${{ env.BUILD_PLATFORM }}.zip"
      - name: Remove symlinks from cpp sdk libs
        env:
          LIB_PATH: "${{ github.workspace }}/${{ env.CPP_SDK_DESTINATION }}/sdk-release/lib"
        run: |
          ls -la ${LIB_PATH}/
          echo "Removing symlinks from ${LIB_PATH}"
          rm ${LIB_PATH}/libav*.dylib
          ls -la ${LIB_PATH}/
      - name: Run Build
        run: |
          /Users/Shared/Epic\ Games/UE_${{ matrix.version }}/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin \
          -Rocket \
          -Plugin=$(pwd)/DolbyIO/DolbyIO.uplugin \
          -TargetPlatforms=Mac \
          -Package=$(pwd)/${{ env.UNREAL_PLUGIN_OUTPUT }} \
          -StrictIncludes
      - name: Zipping DolbIO Plugin
        uses: ./.github/actions/zip_artifact/bash
        with:
          zip_name: "DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip"
          src_dir_path: ${{ env.UNREAL_PLUGIN_OUTPUT }}
      - name: Archive DolbyIO Plugin
        if: contains(fromJson('["refs/heads/main", "refs/heads/develop", "refs/tags"]'), github.ref)
        uses: actions/upload-artifact@v3
        with:
          name: DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip
          path: ./DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip
          retention-days: ${{ env.RETENTION }}
      - name: Create GitHub release
        run: |
          echo "Create GitHub release only for tag."
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        version: ["4.27", "5.0"]
    runs-on: ["self-hosted", "X64", "Windows"]
    env:
      BUILD_PLATFORM: 'windows64'
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Download C++ SDK release asset
        id: download_cpp
        uses: ./.github/actions/download_cpp/powershell
        with:
          url: ${{ env.CPP_SDK_URL }}
          tag: ${{ env.CPP_SDK_TAG }}
          asset_name: "cppsdk-${{ env.CPP_SDK_TAG }}-${{ env.BUILD_PLATFORM }}.zip"
      - name: Run Build
        run: |
          Write-Output "UE_${{ matrix.version }}"
          $UERunUAT = "C:\\Program Files\\Epic Games\\UE_${{ matrix.version }}\\Engine\\Build\\BatchFiles\\RunUAT.bat"
          & $UERunUAT BuildPlugin -Rocket -Plugin="$(pwd)\\DolbyIO\\DolbyIO.uplugin" -TargetPlatforms=Win64 -Package="$(pwd)\\Build\\DolbyIO" -StrictIncludes -VS2019 -NoTurnKeyVariables
      - name: Zipping DolbyIO Plugin
        uses: ./.github/actions/zip_artifact/powershell
        with:
          zip_name: "DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip"
          src_dir_path: ${{ env.UNREAL_PLUGIN_OUTPUT }}
      - name: Archive DolbyIO Plugin
        if: contains(fromJson('["refs/heads/main", "refs/heads/develop", "refs/tags"]'), github.ref)
        uses: actions/upload-artifact@v3
        with:
          name: DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip
          path: ./DolbyIO_UnrealPlugin_${{ matrix.version }}_${{ env.BUILD_PLATFORM }}.zip
          retention-days: ${{ env.RETENTION }}
      - name: Create GitHub release
        run: |
          Write-Output "Create GitHub release only for tag."
